version: '3'

services:
  database:
    image: 'postgres:15-alpine'
    restart: always
    container_name: 'postgres-db'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - web-app
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  web-app:
volumes:
  db-data: